//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System.Collections.Immutable;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System.Text.Json;
using Corvus.Json;
using Corvus.Json.Internal;

namespace ACRealms.RealmProps.IntermediateModels;
public readonly partial struct RealmPropertySchema
{
    /// <summary>
    /// Generated from JSON Schema.
    /// </summary>
    public readonly partial struct GroupEntity
    {
        /// <summary>
        /// The well-known property names in the JSON object.
        /// </summary>
        public static class JsonPropertyNames
        {
            /// <summary>
            /// JSON property name for <see cref = "Default"/>.
            /// </summary>
            public static ReadOnlySpan<byte> DefaultUtf8 => "default"u8;

            /// <summary>
            /// JSON property name for <see cref = "Default"/>.
            /// </summary>
            public const string Default = "default";
            /// <summary>
            /// JSON property name for <see cref = "DescriptionFormat"/>.
            /// </summary>
            public static ReadOnlySpan<byte> DescriptionFormatUtf8 => "description_format"u8;

            /// <summary>
            /// JSON property name for <see cref = "DescriptionFormat"/>.
            /// </summary>
            public const string DescriptionFormat = "description_format";
            /// <summary>
            /// JSON property name for <see cref = "Enum"/>.
            /// </summary>
            public static ReadOnlySpan<byte> EnumUtf8 => "enum"u8;

            /// <summary>
            /// JSON property name for <see cref = "Enum"/>.
            /// </summary>
            public const string Enum = "enum";
            /// <summary>
            /// JSON property name for <see cref = "KeyPrefix"/>.
            /// </summary>
            public static ReadOnlySpan<byte> KeyPrefixUtf8 => "key_prefix"u8;

            /// <summary>
            /// JSON property name for <see cref = "KeyPrefix"/>.
            /// </summary>
            public const string KeyPrefix = "key_prefix";
            /// <summary>
            /// JSON property name for <see cref = "KeySuffix"/>.
            /// </summary>
            public static ReadOnlySpan<byte> KeySuffixUtf8 => "key_suffix"u8;

            /// <summary>
            /// JSON property name for <see cref = "KeySuffix"/>.
            /// </summary>
            public const string KeySuffix = "key_suffix";
            /// <summary>
            /// JSON property name for <see cref = "MaxValue"/>.
            /// </summary>
            public static ReadOnlySpan<byte> MaxValueUtf8 => "max_value"u8;

            /// <summary>
            /// JSON property name for <see cref = "MaxValue"/>.
            /// </summary>
            public const string MaxValue = "max_value";
            /// <summary>
            /// JSON property name for <see cref = "MinValue"/>.
            /// </summary>
            public static ReadOnlySpan<byte> MinValueUtf8 => "min_value"u8;

            /// <summary>
            /// JSON property name for <see cref = "MinValue"/>.
            /// </summary>
            public const string MinValue = "min_value";
            /// <summary>
            /// JSON property name for <see cref = "Properties"/>.
            /// </summary>
            public static ReadOnlySpan<byte> PropertiesUtf8 => "properties"u8;

            /// <summary>
            /// JSON property name for <see cref = "Properties"/>.
            /// </summary>
            public const string Properties = "properties";
            /// <summary>
            /// JSON property name for <see cref = "Type"/>.
            /// </summary>
            public static ReadOnlySpan<byte> TypeUtf8 => "type"u8;

            /// <summary>
            /// JSON property name for <see cref = "Type"/>.
            /// </summary>
            public const string Type = "type";
        }

        /// <summary>
        /// Gets the (optional) <c>default</c> property.
        /// </summary>
        /// <remarks>
        /// <para>
        /// The hard default value for the realm property (ultimate fallback)
        /// </para>
        /// </remarks>
        public ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity.DefaultEntity Default
        {
            get
            {
                if ((this.backing & Backing.JsonElement) != 0)
                {
                    if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                    {
                        return default;
                    }

                    if (this.jsonElementBacking.TryGetProperty(JsonPropertyNames.DefaultUtf8, out JsonElement result))
                    {
                        return new ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity.DefaultEntity(result);
                    }
                }

                if ((this.backing & Backing.Object) != 0)
                {
                    if (this.objectBacking.TryGetValue(JsonPropertyNames.Default, out JsonAny result))
                    {
                        return result.As<ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity.DefaultEntity>();
                    }
                }

                return default;
            }
        }

        /// <summary>
        /// Gets the (optional) <c>description_format</c> property.
        /// </summary>
        public ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ValDescriptionEntity DescriptionFormat
        {
            get
            {
                if ((this.backing & Backing.JsonElement) != 0)
                {
                    if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                    {
                        return default;
                    }

                    if (this.jsonElementBacking.TryGetProperty(JsonPropertyNames.DescriptionFormatUtf8, out JsonElement result))
                    {
                        return new ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ValDescriptionEntity(result);
                    }
                }

                if ((this.backing & Backing.Object) != 0)
                {
                    if (this.objectBacking.TryGetValue(JsonPropertyNames.DescriptionFormat, out JsonAny result))
                    {
                        return result.As<ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ValDescriptionEntity>();
                    }
                }

                return default;
            }
        }

        /// <summary>
        /// Gets the (optional) <c>enum</c> property.
        /// </summary>
        /// <remarks>
        /// <para>
        /// The exact name of the C# Enum class.
        /// </para>
        /// </remarks>
        public Corvus.Json.JsonString Enum
        {
            get
            {
                if ((this.backing & Backing.JsonElement) != 0)
                {
                    if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                    {
                        return default;
                    }

                    if (this.jsonElementBacking.TryGetProperty(JsonPropertyNames.EnumUtf8, out JsonElement result))
                    {
                        return new Corvus.Json.JsonString(result);
                    }
                }

                if ((this.backing & Backing.Object) != 0)
                {
                    if (this.objectBacking.TryGetValue(JsonPropertyNames.Enum, out JsonAny result))
                    {
                        return result.As<Corvus.Json.JsonString>();
                    }
                }

                return default;
            }
        }

        /// <summary>
        /// Gets the (optional) <c>key_prefix</c> property.
        /// </summary>
        /// <remarks>
        /// <para>
        /// Property names in this group will be prefixed with this value
        /// </para>
        /// </remarks>
        public ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.GroupEntity.PropertyNamesInThisGroupWillBePrefixedWithThisValue KeyPrefix
        {
            get
            {
                if ((this.backing & Backing.JsonElement) != 0)
                {
                    if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                    {
                        return default;
                    }

                    if (this.jsonElementBacking.TryGetProperty(JsonPropertyNames.KeyPrefixUtf8, out JsonElement result))
                    {
                        return new ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.GroupEntity.PropertyNamesInThisGroupWillBePrefixedWithThisValue(result);
                    }
                }

                if ((this.backing & Backing.Object) != 0)
                {
                    if (this.objectBacking.TryGetValue(JsonPropertyNames.KeyPrefix, out JsonAny result))
                    {
                        return result.As<ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.GroupEntity.PropertyNamesInThisGroupWillBePrefixedWithThisValue>();
                    }
                }

                return default;
            }
        }

        /// <summary>
        /// Gets the (optional) <c>key_suffix</c> property.
        /// </summary>
        /// <remarks>
        /// <para>
        /// Property names in this group will be suffixed with this value
        /// </para>
        /// </remarks>
        public ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.GroupEntity.PropertyNamesInThisGroupWillBeSuffixedWithThisValue KeySuffix
        {
            get
            {
                if ((this.backing & Backing.JsonElement) != 0)
                {
                    if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                    {
                        return default;
                    }

                    if (this.jsonElementBacking.TryGetProperty(JsonPropertyNames.KeySuffixUtf8, out JsonElement result))
                    {
                        return new ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.GroupEntity.PropertyNamesInThisGroupWillBeSuffixedWithThisValue(result);
                    }
                }

                if ((this.backing & Backing.Object) != 0)
                {
                    if (this.objectBacking.TryGetValue(JsonPropertyNames.KeySuffix, out JsonAny result))
                    {
                        return result.As<ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.GroupEntity.PropertyNamesInThisGroupWillBeSuffixedWithThisValue>();
                    }
                }

                return default;
            }
        }

        /// <summary>
        /// Gets the (optional) <c>max_value</c> property.
        /// </summary>
        public ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ValFloatEntity MaxValue
        {
            get
            {
                if ((this.backing & Backing.JsonElement) != 0)
                {
                    if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                    {
                        return default;
                    }

                    if (this.jsonElementBacking.TryGetProperty(JsonPropertyNames.MaxValueUtf8, out JsonElement result))
                    {
                        return new ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ValFloatEntity(result);
                    }
                }

                if ((this.backing & Backing.Object) != 0)
                {
                    if (this.objectBacking.TryGetValue(JsonPropertyNames.MaxValue, out JsonAny result))
                    {
                        return result.As<ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ValFloatEntity>();
                    }
                }

                return default;
            }
        }

        /// <summary>
        /// Gets the (optional) <c>min_value</c> property.
        /// </summary>
        public ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ValFloatEntity MinValue
        {
            get
            {
                if ((this.backing & Backing.JsonElement) != 0)
                {
                    if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                    {
                        return default;
                    }

                    if (this.jsonElementBacking.TryGetProperty(JsonPropertyNames.MinValueUtf8, out JsonElement result))
                    {
                        return new ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ValFloatEntity(result);
                    }
                }

                if ((this.backing & Backing.Object) != 0)
                {
                    if (this.objectBacking.TryGetValue(JsonPropertyNames.MinValue, out JsonAny result))
                    {
                        return result.As<ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ValFloatEntity>();
                    }
                }

                return default;
            }
        }

        /// <summary>
        /// Gets the (optional) <c>properties</c> property.
        /// </summary>
        public ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropListForGroupEntity Properties
        {
            get
            {
                if ((this.backing & Backing.JsonElement) != 0)
                {
                    if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                    {
                        return default;
                    }

                    if (this.jsonElementBacking.TryGetProperty(JsonPropertyNames.PropertiesUtf8, out JsonElement result))
                    {
                        return new ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropListForGroupEntity(result);
                    }
                }

                if ((this.backing & Backing.Object) != 0)
                {
                    if (this.objectBacking.TryGetValue(JsonPropertyNames.Properties, out JsonAny result))
                    {
                        return result.As<ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropListForGroupEntity>();
                    }
                }

                return default;
            }
        }

        /// <summary>
        /// Gets the (optional) <c>type</c> property.
        /// </summary>
        public ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.PropertytypeEntity Type
        {
            get
            {
                if ((this.backing & Backing.JsonElement) != 0)
                {
                    if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                    {
                        return default;
                    }

                    if (this.jsonElementBacking.TryGetProperty(JsonPropertyNames.TypeUtf8, out JsonElement result))
                    {
                        return new ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.PropertytypeEntity(result);
                    }
                }

                if ((this.backing & Backing.Object) != 0)
                {
                    if (this.objectBacking.TryGetValue(JsonPropertyNames.Type, out JsonAny result))
                    {
                        return result.As<ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.PropertytypeEntity>();
                    }
                }

                return default;
            }
        }

        /// <summary>
        /// Creates an instance of a <see cref = "GroupEntity"/>.
        /// </summary>
        public static GroupEntity Create(ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity.DefaultEntity? @default = null, ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ValDescriptionEntity? descriptionFormat = null, Corvus.Json.JsonString? @enum = null, ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.GroupEntity.PropertyNamesInThisGroupWillBePrefixedWithThisValue? keyPrefix = null, ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.GroupEntity.PropertyNamesInThisGroupWillBeSuffixedWithThisValue? keySuffix = null, ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ValFloatEntity? maxValue = null, ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ValFloatEntity? minValue = null, ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropListForGroupEntity? properties = null, ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.PropertytypeEntity? type = null)
        {
            var builder = ImmutableList.CreateBuilder<JsonObjectProperty>();
            if (@default is ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity.DefaultEntity @default__)
            {
                builder.Add(JsonPropertyNames.Default, @default__.AsAny);
            }

            if (descriptionFormat is ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ValDescriptionEntity descriptionFormat__)
            {
                builder.Add(JsonPropertyNames.DescriptionFormat, descriptionFormat__.AsAny);
            }

            if (@enum is Corvus.Json.JsonString @enum__)
            {
                builder.Add(JsonPropertyNames.Enum, @enum__.AsAny);
            }

            if (keyPrefix is ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.GroupEntity.PropertyNamesInThisGroupWillBePrefixedWithThisValue keyPrefix__)
            {
                builder.Add(JsonPropertyNames.KeyPrefix, keyPrefix__.AsAny);
            }

            if (keySuffix is ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.GroupEntity.PropertyNamesInThisGroupWillBeSuffixedWithThisValue keySuffix__)
            {
                builder.Add(JsonPropertyNames.KeySuffix, keySuffix__.AsAny);
            }

            if (maxValue is ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ValFloatEntity maxValue__)
            {
                builder.Add(JsonPropertyNames.MaxValue, maxValue__.AsAny);
            }

            if (minValue is ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ValFloatEntity minValue__)
            {
                builder.Add(JsonPropertyNames.MinValue, minValue__.AsAny);
            }

            if (properties is ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropListForGroupEntity properties__)
            {
                builder.Add(JsonPropertyNames.Properties, properties__.AsAny);
            }

            if (type is ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.PropertytypeEntity type__)
            {
                builder.Add(JsonPropertyNames.Type, type__.AsAny);
            }

            return new(builder.ToImmutable());
        }

        /// <summary>
        /// Sets default.
        /// </summary>
        /// <param name = "value">The value to set.</param>
        /// <returns>The entity with the updated property.</returns>
        public GroupEntity WithDefault(in ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity.DefaultEntity value)
        {
            return this.SetProperty(JsonPropertyNames.Default, value);
        }

        /// <summary>
        /// Sets description_format.
        /// </summary>
        /// <param name = "value">The value to set.</param>
        /// <returns>The entity with the updated property.</returns>
        public GroupEntity WithDescriptionFormat(in ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ValDescriptionEntity value)
        {
            return this.SetProperty(JsonPropertyNames.DescriptionFormat, value);
        }

        /// <summary>
        /// Sets enum.
        /// </summary>
        /// <param name = "value">The value to set.</param>
        /// <returns>The entity with the updated property.</returns>
        public GroupEntity WithEnum(in Corvus.Json.JsonString value)
        {
            return this.SetProperty(JsonPropertyNames.Enum, value);
        }

        /// <summary>
        /// Sets key_prefix.
        /// </summary>
        /// <param name = "value">The value to set.</param>
        /// <returns>The entity with the updated property.</returns>
        public GroupEntity WithKeyPrefix(in ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.GroupEntity.PropertyNamesInThisGroupWillBePrefixedWithThisValue value)
        {
            return this.SetProperty(JsonPropertyNames.KeyPrefix, value);
        }

        /// <summary>
        /// Sets key_suffix.
        /// </summary>
        /// <param name = "value">The value to set.</param>
        /// <returns>The entity with the updated property.</returns>
        public GroupEntity WithKeySuffix(in ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.GroupEntity.PropertyNamesInThisGroupWillBeSuffixedWithThisValue value)
        {
            return this.SetProperty(JsonPropertyNames.KeySuffix, value);
        }

        /// <summary>
        /// Sets max_value.
        /// </summary>
        /// <param name = "value">The value to set.</param>
        /// <returns>The entity with the updated property.</returns>
        public GroupEntity WithMaxValue(in ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ValFloatEntity value)
        {
            return this.SetProperty(JsonPropertyNames.MaxValue, value);
        }

        /// <summary>
        /// Sets min_value.
        /// </summary>
        /// <param name = "value">The value to set.</param>
        /// <returns>The entity with the updated property.</returns>
        public GroupEntity WithMinValue(in ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ValFloatEntity value)
        {
            return this.SetProperty(JsonPropertyNames.MinValue, value);
        }

        /// <summary>
        /// Sets properties.
        /// </summary>
        /// <param name = "value">The value to set.</param>
        /// <returns>The entity with the updated property.</returns>
        public GroupEntity WithProperties(in ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropListForGroupEntity value)
        {
            return this.SetProperty(JsonPropertyNames.Properties, value);
        }

        /// <summary>
        /// Sets type.
        /// </summary>
        /// <param name = "value">The value to set.</param>
        /// <returns>The entity with the updated property.</returns>
        public GroupEntity WithType(in ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.PropertytypeEntity value)
        {
            return this.SetProperty(JsonPropertyNames.Type, value);
        }

        private static ValidationContext __CorvusValidateDescriptionFormat(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
        {
            return property.ValueAs<ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ValDescriptionEntity>().Validate(validationContext, level);
        }

        private static ValidationContext __CorvusValidateKeyPrefix(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
        {
            return property.ValueAs<ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.GroupEntity.PropertyNamesInThisGroupWillBePrefixedWithThisValue>().Validate(validationContext, level);
        }

        private static ValidationContext __CorvusValidateKeySuffix(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
        {
            return property.ValueAs<ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.GroupEntity.PropertyNamesInThisGroupWillBeSuffixedWithThisValue>().Validate(validationContext, level);
        }

        private static ValidationContext __CorvusValidateProperties(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
        {
            return property.ValueAs<ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropListForGroupEntity>().Validate(validationContext, level);
        }

        /// <summary>
        /// Tries to get the validator for the given property.
        /// </summary>
        /// <param name = "property">The property for which to get the validator.</param>
        /// <param name = "hasJsonElementBacking"><c>True</c> if the object containing the property has a JsonElement backing.</param>
        /// <param name = "propertyValidator">The validator for the property, if provided by this schema.</param>
        /// <returns><c>True</c> if the validator was found.</returns>
        private bool __TryGetCorvusLocalPropertiesValidator(in JsonObjectProperty property, bool hasJsonElementBacking, [NotNullWhen(true)] out ObjectPropertyValidator? propertyValidator)
        {
            if (hasJsonElementBacking)
            {
                if (property.NameEquals(JsonPropertyNames.DescriptionFormatUtf8))
                {
                    propertyValidator = __CorvusValidateDescriptionFormat;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.KeyPrefixUtf8))
                {
                    propertyValidator = __CorvusValidateKeyPrefix;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.KeySuffixUtf8))
                {
                    propertyValidator = __CorvusValidateKeySuffix;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.PropertiesUtf8))
                {
                    propertyValidator = __CorvusValidateProperties;
                    return true;
                }
            }
            else
            {
                if (property.NameEquals(JsonPropertyNames.DescriptionFormat))
                {
                    propertyValidator = __CorvusValidateDescriptionFormat;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.KeyPrefix))
                {
                    propertyValidator = __CorvusValidateKeyPrefix;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.KeySuffix))
                {
                    propertyValidator = __CorvusValidateKeySuffix;
                    return true;
                }
                else if (property.NameEquals(JsonPropertyNames.Properties))
                {
                    propertyValidator = __CorvusValidateProperties;
                    return true;
                }
            }

            propertyValidator = null;
            return false;
        }
    }
}