//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System.Collections.Immutable;
using System.Runtime.CompilerServices;
using System.Text.Json;
using Corvus.Json;
using Corvus.Json.Internal;

namespace ACRealms.RealmProps.IntermediateModels;
public readonly partial struct RealmPropertySchema
{
    /// <summary>
    /// Generated from JSON Schema.
    /// </summary>
    public readonly partial struct SchemaVersionEntity
    {
        private static readonly SchemaVersionEntity __CorvusConstValue = SchemaVersionEntity.ParseValue("1"u8);
        /// <summary>
        /// Initializes a new instance of the <see cref = "SchemaVersionEntity"/> struct.
        /// </summary>
        public SchemaVersionEntity()
        {
            this.jsonElementBacking = __CorvusConstValue.jsonElementBacking;
            this.numberBacking = __CorvusConstValue.numberBacking;
            this.backing = __CorvusConstValue.backing;
        }

        /// <summary>
        /// Gets the constant value for this instance
        /// </summary>
        public static SchemaVersionEntity ConstInstance => __CorvusConstValue;
    }
}