//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System.Collections.Immutable;
using System.Text.Json;
using Corvus.Json;
using Corvus.Json.Internal;

namespace ACRealms.RealmProps.IntermediateModels;
public readonly partial struct RealmPropertySchema
{
    /// <summary>
    /// Generated from JSON Schema.
    /// </summary>
    public readonly partial struct PropDefEntity
    {
        /// <summary>
        /// Conversion to <see cref = "ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropEntity"/>.
        /// </summary>
        /// <param name = "value">The value from which to convert.</param>
        public static explicit operator ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropEntity(PropDefEntity value)
        {
            if ((value.backing & Backing.JsonElement) != 0)
            {
                return new(value.AsJsonElement);
            }

            if ((value.backing & Backing.Object) != 0)
            {
                return new(value.objectBacking);
            }

            return ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropEntity.Undefined;
        }

        /// <summary>
        /// Conversion from <see cref = "ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropEntity"/>.
        /// </summary>
        /// <param name = "value">The value from which to convert.</param>
        public static implicit operator PropDefEntity(ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropEntity value)
        {
            if (value.HasJsonElementBacking)
            {
                return new(value.AsJsonElement);
            }

            return value.ValueKind switch
            {
                JsonValueKind.Object => new(value.AsPropertyBacking()),
                _ => Undefined
            };
        }

        /// <summary>
        /// Conversion to <see cref = "ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity"/>.
        /// </summary>
        /// <param name = "value">The value from which to convert.</param>
        public static implicit operator ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity(PropDefEntity value)
        {
            if ((value.backing & Backing.JsonElement) != 0)
            {
                return new(value.AsJsonElement);
            }

            if ((value.backing & Backing.Object) != 0)
            {
                return new(value.objectBacking);
            }

            return ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity.Undefined;
        }

        /// <summary>
        /// Conversion from <see cref = "ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity"/>.
        /// </summary>
        /// <param name = "value">The value from which to convert.</param>
        public static explicit operator PropDefEntity(ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity value)
        {
            if (value.HasJsonElementBacking)
            {
                return new(value.AsJsonElement);
            }

            return value.ValueKind switch
            {
                JsonValueKind.Object => new(value.AsPropertyBacking()),
                _ => Undefined
            };
        }

        /// <summary>
        /// Conversion to <see cref = "ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity.AllOf0Entity"/>.
        /// </summary>
        /// <param name = "value">The value from which to convert.</param>
        public static implicit operator ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity.AllOf0Entity(PropDefEntity value)
        {
            if ((value.backing & Backing.JsonElement) != 0)
            {
                return new(value.AsJsonElement);
            }

            if ((value.backing & Backing.Object) != 0)
            {
                return new(value.objectBacking);
            }

            return ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity.AllOf0Entity.Undefined;
        }

        /// <summary>
        /// Conversion from <see cref = "ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity.AllOf0Entity"/>.
        /// </summary>
        /// <param name = "value">The value from which to convert.</param>
        public static explicit operator PropDefEntity(ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity.AllOf0Entity value)
        {
            if (value.HasJsonElementBacking)
            {
                return new(value.AsJsonElement);
            }

            return value.ValueKind switch
            {
                JsonValueKind.Object => new(value.AsPropertyBacking()),
                _ => Undefined
            };
        }

        /// <summary>
        /// Conversion to <see cref = "ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity.AllOf0Entity.WithTypeEnum"/>.
        /// </summary>
        /// <param name = "value">The value from which to convert.</param>
        public static explicit operator ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity.AllOf0Entity.WithTypeEnum(PropDefEntity value)
        {
            if ((value.backing & Backing.JsonElement) != 0)
            {
                return new(value.AsJsonElement);
            }

            if ((value.backing & Backing.Object) != 0)
            {
                return new(value.objectBacking);
            }

            return ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity.AllOf0Entity.WithTypeEnum.Undefined;
        }

        /// <summary>
        /// Conversion from <see cref = "ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity.AllOf0Entity.WithTypeEnum"/>.
        /// </summary>
        /// <param name = "value">The value from which to convert.</param>
        public static explicit operator PropDefEntity(ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity.AllOf0Entity.WithTypeEnum value)
        {
            if (value.HasJsonElementBacking)
            {
                return new(value.AsJsonElement);
            }

            return value.ValueKind switch
            {
                JsonValueKind.Object => new(value.AsPropertyBacking()),
                _ => Undefined
            };
        }

        /// <summary>
        /// Conversion to <see cref = "ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity.AllOf1Entity"/>.
        /// </summary>
        /// <param name = "value">The value from which to convert.</param>
        public static implicit operator ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity.AllOf1Entity(PropDefEntity value)
        {
            if ((value.backing & Backing.JsonElement) != 0)
            {
                return new(value.AsJsonElement);
            }

            if ((value.backing & Backing.Object) != 0)
            {
                return new(value.objectBacking);
            }

            return ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity.AllOf1Entity.Undefined;
        }

        /// <summary>
        /// Conversion from <see cref = "ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity.AllOf1Entity"/>.
        /// </summary>
        /// <param name = "value">The value from which to convert.</param>
        public static explicit operator PropDefEntity(ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity.AllOf1Entity value)
        {
            if (value.HasJsonElementBacking)
            {
                return new(value.AsJsonElement);
            }

            return value.ValueKind switch
            {
                JsonValueKind.Object => new(value.AsPropertyBacking()),
                _ => Undefined
            };
        }

        /// <summary>
        /// Conversion to <see cref = "ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity.AllOf1Entity.RequiredEnum"/>.
        /// </summary>
        /// <param name = "value">The value from which to convert.</param>
        public static explicit operator ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity.AllOf1Entity.RequiredEnum(PropDefEntity value)
        {
            if ((value.backing & Backing.JsonElement) != 0)
            {
                return new(value.AsJsonElement);
            }

            if ((value.backing & Backing.Object) != 0)
            {
                return new(value.objectBacking);
            }

            return ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity.AllOf1Entity.RequiredEnum.Undefined;
        }

        /// <summary>
        /// Conversion from <see cref = "ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity.AllOf1Entity.RequiredEnum"/>.
        /// </summary>
        /// <param name = "value">The value from which to convert.</param>
        public static explicit operator PropDefEntity(ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity.AllOf1Entity.RequiredEnum value)
        {
            if (value.HasJsonElementBacking)
            {
                return new(value.AsJsonElement);
            }

            return value.ValueKind switch
            {
                JsonValueKind.Object => new(value.AsPropertyBacking()),
                _ => Undefined
            };
        }

        /// <summary>
        /// Conversion to <see cref = "ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity.AllOf2Entity"/>.
        /// </summary>
        /// <param name = "value">The value from which to convert.</param>
        public static implicit operator ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity.AllOf2Entity(PropDefEntity value)
        {
            if ((value.backing & Backing.JsonElement) != 0)
            {
                return new(value.AsJsonElement);
            }

            if ((value.backing & Backing.Object) != 0)
            {
                return new(value.objectBacking);
            }

            return ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity.AllOf2Entity.Undefined;
        }

        /// <summary>
        /// Conversion from <see cref = "ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity.AllOf2Entity"/>.
        /// </summary>
        /// <param name = "value">The value from which to convert.</param>
        public static explicit operator PropDefEntity(ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity.AllOf2Entity value)
        {
            if (value.HasJsonElementBacking)
            {
                return new(value.AsJsonElement);
            }

            return value.ValueKind switch
            {
                JsonValueKind.Object => new(value.AsPropertyBacking()),
                _ => Undefined
            };
        }

        /// <summary>
        /// Conversion to <see cref = "ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity.AllOf2Entity.ThenEntity"/>.
        /// </summary>
        /// <param name = "value">The value from which to convert.</param>
        public static explicit operator ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity.AllOf2Entity.ThenEntity(PropDefEntity value)
        {
            if ((value.backing & Backing.JsonElement) != 0)
            {
                return new(value.AsJsonElement);
            }

            if ((value.backing & Backing.Object) != 0)
            {
                return new(value.objectBacking);
            }

            return ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity.AllOf2Entity.ThenEntity.Undefined;
        }

        /// <summary>
        /// Conversion from <see cref = "ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity.AllOf2Entity.ThenEntity"/>.
        /// </summary>
        /// <param name = "value">The value from which to convert.</param>
        public static explicit operator PropDefEntity(ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity.AllOf2Entity.ThenEntity value)
        {
            if (value.HasJsonElementBacking)
            {
                return new(value.AsJsonElement);
            }

            return value.ValueKind switch
            {
                JsonValueKind.Object => new(value.AsPropertyBacking()),
                _ => Undefined
            };
        }

        /// <summary>
        /// Conversion to <see cref = "ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity.AllOf3Entity"/>.
        /// </summary>
        /// <param name = "value">The value from which to convert.</param>
        public static implicit operator ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity.AllOf3Entity(PropDefEntity value)
        {
            if ((value.backing & Backing.JsonElement) != 0)
            {
                return new(value.AsJsonElement);
            }

            if ((value.backing & Backing.Object) != 0)
            {
                return new(value.objectBacking);
            }

            return ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity.AllOf3Entity.Undefined;
        }

        /// <summary>
        /// Conversion from <see cref = "ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity.AllOf3Entity"/>.
        /// </summary>
        /// <param name = "value">The value from which to convert.</param>
        public static explicit operator PropDefEntity(ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity.AllOf3Entity value)
        {
            if (value.HasJsonElementBacking)
            {
                return new(value.AsJsonElement);
            }

            return value.ValueKind switch
            {
                JsonValueKind.Object => new(value.AsPropertyBacking()),
                _ => Undefined
            };
        }

        /// <summary>
        /// Conversion to <see cref = "ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity.AllOf3Entity.ThenEntity"/>.
        /// </summary>
        /// <param name = "value">The value from which to convert.</param>
        public static explicit operator ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity.AllOf3Entity.ThenEntity(PropDefEntity value)
        {
            if ((value.backing & Backing.JsonElement) != 0)
            {
                return new(value.AsJsonElement);
            }

            if ((value.backing & Backing.Object) != 0)
            {
                return new(value.objectBacking);
            }

            return ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity.AllOf3Entity.ThenEntity.Undefined;
        }

        /// <summary>
        /// Conversion from <see cref = "ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity.AllOf3Entity.ThenEntity"/>.
        /// </summary>
        /// <param name = "value">The value from which to convert.</param>
        public static explicit operator PropDefEntity(ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity.AllOf3Entity.ThenEntity value)
        {
            if (value.HasJsonElementBacking)
            {
                return new(value.AsJsonElement);
            }

            return value.ValueKind switch
            {
                JsonValueKind.Object => new(value.AsPropertyBacking()),
                _ => Undefined
            };
        }

        /// <summary>
        /// Conversion to <see cref = "ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity.AllOf4Entity"/>.
        /// </summary>
        /// <param name = "value">The value from which to convert.</param>
        public static implicit operator ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity.AllOf4Entity(PropDefEntity value)
        {
            if ((value.backing & Backing.JsonElement) != 0)
            {
                return new(value.AsJsonElement);
            }

            if ((value.backing & Backing.Object) != 0)
            {
                return new(value.objectBacking);
            }

            return ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity.AllOf4Entity.Undefined;
        }

        /// <summary>
        /// Conversion from <see cref = "ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity.AllOf4Entity"/>.
        /// </summary>
        /// <param name = "value">The value from which to convert.</param>
        public static explicit operator PropDefEntity(ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity.AllOf4Entity value)
        {
            if (value.HasJsonElementBacking)
            {
                return new(value.AsJsonElement);
            }

            return value.ValueKind switch
            {
                JsonValueKind.Object => new(value.AsPropertyBacking()),
                _ => Undefined
            };
        }

        /// <summary>
        /// Conversion to <see cref = "ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity.AllOf4Entity.ThenEntity"/>.
        /// </summary>
        /// <param name = "value">The value from which to convert.</param>
        public static explicit operator ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity.AllOf4Entity.ThenEntity(PropDefEntity value)
        {
            if ((value.backing & Backing.JsonElement) != 0)
            {
                return new(value.AsJsonElement);
            }

            if ((value.backing & Backing.Object) != 0)
            {
                return new(value.objectBacking);
            }

            return ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity.AllOf4Entity.ThenEntity.Undefined;
        }

        /// <summary>
        /// Conversion from <see cref = "ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity.AllOf4Entity.ThenEntity"/>.
        /// </summary>
        /// <param name = "value">The value from which to convert.</param>
        public static explicit operator PropDefEntity(ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity.AllOf4Entity.ThenEntity value)
        {
            if (value.HasJsonElementBacking)
            {
                return new(value.AsJsonElement);
            }

            return value.ValueKind switch
            {
                JsonValueKind.Object => new(value.AsPropertyBacking()),
                _ => Undefined
            };
        }

        /// <summary>
        /// Conversion to <see cref = "ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity.AllOf5Entity"/>.
        /// </summary>
        /// <param name = "value">The value from which to convert.</param>
        public static implicit operator ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity.AllOf5Entity(PropDefEntity value)
        {
            if ((value.backing & Backing.JsonElement) != 0)
            {
                return new(value.AsJsonElement);
            }

            if ((value.backing & Backing.Object) != 0)
            {
                return new(value.objectBacking);
            }

            return ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity.AllOf5Entity.Undefined;
        }

        /// <summary>
        /// Conversion from <see cref = "ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity.AllOf5Entity"/>.
        /// </summary>
        /// <param name = "value">The value from which to convert.</param>
        public static explicit operator PropDefEntity(ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity.AllOf5Entity value)
        {
            if (value.HasJsonElementBacking)
            {
                return new(value.AsJsonElement);
            }

            return value.ValueKind switch
            {
                JsonValueKind.Object => new(value.AsPropertyBacking()),
                _ => Undefined
            };
        }

        /// <summary>
        /// Conversion to <see cref = "ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity.AllOf5Entity.ThenEntity"/>.
        /// </summary>
        /// <param name = "value">The value from which to convert.</param>
        public static explicit operator ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity.AllOf5Entity.ThenEntity(PropDefEntity value)
        {
            if ((value.backing & Backing.JsonElement) != 0)
            {
                return new(value.AsJsonElement);
            }

            if ((value.backing & Backing.Object) != 0)
            {
                return new(value.objectBacking);
            }

            return ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity.AllOf5Entity.ThenEntity.Undefined;
        }

        /// <summary>
        /// Conversion from <see cref = "ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity.AllOf5Entity.ThenEntity"/>.
        /// </summary>
        /// <param name = "value">The value from which to convert.</param>
        public static explicit operator PropDefEntity(ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity.AllOf5Entity.ThenEntity value)
        {
            if (value.HasJsonElementBacking)
            {
                return new(value.AsJsonElement);
            }

            return value.ValueKind switch
            {
                JsonValueKind.Object => new(value.AsPropertyBacking()),
                _ => Undefined
            };
        }

        /// <summary>
        /// Conversion to <see cref = "ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity.AllOf6Entity"/>.
        /// </summary>
        /// <param name = "value">The value from which to convert.</param>
        public static implicit operator ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity.AllOf6Entity(PropDefEntity value)
        {
            if ((value.backing & Backing.JsonElement) != 0)
            {
                return new(value.AsJsonElement);
            }

            if ((value.backing & Backing.Object) != 0)
            {
                return new(value.objectBacking);
            }

            return ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity.AllOf6Entity.Undefined;
        }

        /// <summary>
        /// Conversion from <see cref = "ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity.AllOf6Entity"/>.
        /// </summary>
        /// <param name = "value">The value from which to convert.</param>
        public static explicit operator PropDefEntity(ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity.AllOf6Entity value)
        {
            if (value.HasJsonElementBacking)
            {
                return new(value.AsJsonElement);
            }

            return value.ValueKind switch
            {
                JsonValueKind.Object => new(value.AsPropertyBacking()),
                _ => Undefined
            };
        }

        /// <summary>
        /// Conversion to <see cref = "ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity.AllOf6Entity.ThenEntity"/>.
        /// </summary>
        /// <param name = "value">The value from which to convert.</param>
        public static explicit operator ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity.AllOf6Entity.ThenEntity(PropDefEntity value)
        {
            if ((value.backing & Backing.JsonElement) != 0)
            {
                return new(value.AsJsonElement);
            }

            if ((value.backing & Backing.Object) != 0)
            {
                return new(value.objectBacking);
            }

            return ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity.AllOf6Entity.ThenEntity.Undefined;
        }

        /// <summary>
        /// Conversion from <see cref = "ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity.AllOf6Entity.ThenEntity"/>.
        /// </summary>
        /// <param name = "value">The value from which to convert.</param>
        public static explicit operator PropDefEntity(ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropOrGroupEntity.AllOf6Entity.ThenEntity value)
        {
            if (value.HasJsonElementBacking)
            {
                return new(value.AsJsonElement);
            }

            return value.ValueKind switch
            {
                JsonValueKind.Object => new(value.AsPropertyBacking()),
                _ => Undefined
            };
        }

        /// <summary>
        /// Conversion to <see cref = "ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ValStringEntity"/>.
        /// </summary>
        /// <param name = "value">The value from which to convert.</param>
        public static explicit operator ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ValStringEntity(PropDefEntity value)
        {
            if ((value.backing & Backing.JsonElement) != 0)
            {
                return new(value.AsJsonElement);
            }

            return ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ValStringEntity.Undefined;
        }

        /// <summary>
        /// Conversion from <see cref = "ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ValStringEntity"/>.
        /// </summary>
        /// <param name = "value">The value from which to convert.</param>
        public static implicit operator PropDefEntity(ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ValStringEntity value)
        {
            if (value.HasJsonElementBacking)
            {
                return new(value.AsJsonElement);
            }

            return value.ValueKind switch
            {
                _ => Undefined
            };
        }

        /// <summary>
        /// Conversion to <see cref = "ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ValStringEntity.OneOf0Entity"/>.
        /// </summary>
        /// <param name = "value">The value from which to convert.</param>
        public static explicit operator ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ValStringEntity.OneOf0Entity(PropDefEntity value)
        {
            if ((value.backing & Backing.JsonElement) != 0)
            {
                return new(value.AsJsonElement);
            }

            if ((value.backing & Backing.String) != 0)
            {
                return new(value.stringBacking);
            }

            return ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ValStringEntity.OneOf0Entity.Undefined;
        }

        /// <summary>
        /// Conversion from <see cref = "ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ValStringEntity.OneOf0Entity"/>.
        /// </summary>
        /// <param name = "value">The value from which to convert.</param>
        public static implicit operator PropDefEntity(ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ValStringEntity.OneOf0Entity value)
        {
            if (value.HasJsonElementBacking)
            {
                return new(value.AsJsonElement);
            }

            return value.ValueKind switch
            {
                JsonValueKind.String => new((string)value),
                _ => Undefined
            };
        }

        /// <summary>
        /// Conversion to <see cref = "ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ValStringEntity.Type1EntityArray"/>.
        /// </summary>
        /// <param name = "value">The value from which to convert.</param>
        public static explicit operator ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ValStringEntity.Type1EntityArray(PropDefEntity value)
        {
            if ((value.backing & Backing.JsonElement) != 0)
            {
                return new(value.AsJsonElement);
            }

            if ((value.backing & Backing.Array) != 0)
            {
                return new(value.arrayBacking);
            }

            return ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ValStringEntity.Type1EntityArray.Undefined;
        }

        /// <summary>
        /// Conversion from <see cref = "ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ValStringEntity.Type1EntityArray"/>.
        /// </summary>
        /// <param name = "value">The value from which to convert.</param>
        public static implicit operator PropDefEntity(ACRealms.RealmProps.IntermediateModels.RealmPropertySchema.ValStringEntity.Type1EntityArray value)
        {
            if (value.HasJsonElementBacking)
            {
                return new(value.AsJsonElement);
            }

            return value.ValueKind switch
            {
                JsonValueKind.Array => new(value.AsImmutableList()),
                _ => Undefined
            };
        }
    }
}