//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using System.Buffers;
using System.Collections.Immutable;
using System.Runtime.CompilerServices;
using System.Text.Json;
using Corvus.Json;
using Corvus.Json.Internal;

namespace ACRealms.Roslyn.RealmProps.IntermediateModels;

/// <summary>
/// Generated from JSON Schema.
/// </summary>
public readonly partial struct RealmPropertySchema
{
    /// <summary>
    /// Generated from JSON Schema.
    /// </summary>
    [System.Text.Json.Serialization.JsonConverter(typeof(Corvus.Json.Internal.JsonValueConverter<ObjPropListForGroup>))]
    public readonly partial struct ObjPropListForGroup
        : IJsonValue<ACRealms.Roslyn.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropListForGroup>
    {
        private readonly Backing backing;
        private readonly JsonElement jsonElementBacking;
        private readonly ImmutableList<JsonAny> arrayBacking;
        private readonly ImmutableList<JsonObjectProperty> objectBacking;

        /// <summary>
        /// Initializes a new instance of the <see cref="ObjPropListForGroup"/> struct.
        /// </summary>
        public ObjPropListForGroup()
        {
            this.jsonElementBacking = default;
            this.backing = Backing.JsonElement;
            this.arrayBacking = ImmutableList<JsonAny>.Empty;
            this.objectBacking = ImmutableList<JsonObjectProperty>.Empty;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ObjPropListForGroup"/> struct.
        /// </summary>
        /// <param name="value">The value from which to construct the instance.</param>
        public ObjPropListForGroup(in JsonElement value)
        {
            this.jsonElementBacking = value;
            this.backing = Backing.JsonElement;
            this.arrayBacking = ImmutableList<JsonAny>.Empty;
            this.objectBacking = ImmutableList<JsonObjectProperty>.Empty;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ObjPropListForGroup"/> struct.
        /// </summary>
        /// <param name="value">The value from which to construct the instance.</param>
        public ObjPropListForGroup(ImmutableList<JsonAny> value)
        {
            this.backing = Backing.Array;
            this.jsonElementBacking = default;
            this.arrayBacking = value;
            this.objectBacking = ImmutableList<JsonObjectProperty>.Empty;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ObjPropListForGroup"/> struct.
        /// </summary>
        /// <param name="value">The value from which to construct the instance.</param>
        public ObjPropListForGroup(ImmutableList<JsonObjectProperty> value)
        {
            this.backing = Backing.Object;
            this.jsonElementBacking = default;
            this.arrayBacking = ImmutableList<JsonAny>.Empty;
            this.objectBacking = value;
        }

        /// <summary>
        /// Gets the schema location from which this type was generated.
        /// </summary>
        public static string SchemaLocation { get; } = "#/definitions/objPropListForGroup";

        /// <summary>
        /// Gets a Null instance.
        /// </summary>
        public static ObjPropListForGroup Null { get; } = new(JsonValueHelpers.NullElement);

        /// <summary>
        /// Gets an Undefined instance.
        /// </summary>
        public static ObjPropListForGroup Undefined { get; }

        /// <summary>
        /// Gets the default instance.
        /// </summary>
        public static ObjPropListForGroup DefaultInstance { get; }

        /// <inheritdoc/>
        public JsonAny AsAny
        {
            get
            {
                if ((this.backing & Backing.JsonElement) != 0)
                {
                    return new(this.jsonElementBacking);
                }

                if ((this.backing & Backing.Array) != 0)
                {
                    return new(this.arrayBacking);
                }

                if ((this.backing & Backing.Object) != 0)
                {
                    return new(this.objectBacking);
                }

                if ((this.backing & Backing.Null) != 0)
                {
                    return JsonAny.Null;
                }

                return JsonAny.Undefined;
            }
        }

        /// <inheritdoc/>
        public JsonElement AsJsonElement
        {
            get
            {
                if ((this.backing & Backing.JsonElement) != 0)
                {
                    return this.jsonElementBacking;
                }

                if ((this.backing & Backing.Array) != 0)
                {
                    return JsonValueHelpers.ArrayToJsonElement(this.arrayBacking);
                }

                if ((this.backing & Backing.Object) != 0)
                {
                    return JsonValueHelpers.ObjectToJsonElement(this.objectBacking);
                }

                if ((this.backing & Backing.Null) != 0)
                {
                    return JsonValueHelpers.NullElement;
                }

                return default;
            }
        }

        /// <inheritdoc/>
        JsonString IJsonValue.AsString
        {
            get
            {
                if ((this.backing & Backing.JsonElement) != 0)
                {
                    return new(this.jsonElementBacking);
                }

                throw new InvalidOperationException();
            }
        }

        /// <inheritdoc/>
        JsonBoolean IJsonValue.AsBoolean
        {
            get
            {
                if ((this.backing & Backing.JsonElement) != 0)
                {
                    return new(this.jsonElementBacking);
                }

                throw new InvalidOperationException();
            }
        }

        /// <inheritdoc/>
        JsonNumber IJsonValue.AsNumber
        {
            get
            {
                if ((this.backing & Backing.JsonElement) != 0)
                {
                    return new(this.jsonElementBacking);
                }

                throw new InvalidOperationException();
            }
        }

        /// <inheritdoc/>
        public JsonObject AsObject
        {
            get
            {
                if ((this.backing & Backing.JsonElement) != 0)
                {
                    return new(this.jsonElementBacking);
                }

                if ((this.backing & Backing.Object) != 0)
                {
                    return new(this.objectBacking);
                }

                throw new InvalidOperationException();
            }
        }

        /// <inheritdoc/>
        public JsonArray AsArray
        {
            get
            {
                if ((this.backing & Backing.JsonElement) != 0)
                {
                    return new(this.jsonElementBacking);
                }

                if ((this.backing & Backing.Array) != 0)
                {
                    return new(this.arrayBacking);
                }

                throw new InvalidOperationException();
            }
        }

        /// <summary>
        /// Gets the instance as a <see cref="ACRealms.Roslyn.RealmProps.IntermediateModels.RealmPropertySchema.ArrayShortPropListForGroup" />.
        /// </summary>
        public ACRealms.Roslyn.RealmProps.IntermediateModels.RealmPropertySchema.ArrayShortPropListForGroup AsArrayShortPropListForGroup
        {
            get
            {
                return this.As<ACRealms.Roslyn.RealmProps.IntermediateModels.RealmPropertySchema.ArrayShortPropListForGroup>();
            }
        }

        /// <summary>
        /// Gets a value indicating whether the instance is a <see cref="ACRealms.Roslyn.RealmProps.IntermediateModels.RealmPropertySchema.ArrayShortPropListForGroup" />.
        /// </summary>
        public bool IsArrayShortPropListForGroup
        {
            get
            {
                return this.As<ACRealms.Roslyn.RealmProps.IntermediateModels.RealmPropertySchema.ArrayShortPropListForGroup>().IsValid();
            }
        }

        /// <summary>
        /// Gets the instance as a <see cref="ACRealms.Roslyn.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropList" />.
        /// </summary>
        public ACRealms.Roslyn.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropList AsObjPropList
        {
            get
            {
                return this.As<ACRealms.Roslyn.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropList>();
            }
        }

        /// <summary>
        /// Gets a value indicating whether the instance is a <see cref="ACRealms.Roslyn.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropList" />.
        /// </summary>
        public bool IsObjPropList
        {
            get
            {
                return this.As<ACRealms.Roslyn.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropList>().IsValid();
            }
        }

        /// <inheritdoc/>
        public bool HasJsonElementBacking
        {
            get
            {
                return (this.backing & Backing.JsonElement) != 0;
            }
        }

        /// <inheritdoc/>
        public bool HasDotnetBacking
        {
            get
            {
                return (this.backing & Backing.Dotnet) != 0;
            }
        }

        /// <inheritdoc/>
        public JsonValueKind ValueKind
        {
            get
            {
                if ((this.backing & Backing.JsonElement) != 0)
                {
                    return this.jsonElementBacking.ValueKind;
                }

                if ((this.backing & Backing.Array) != 0)
                {
                    return JsonValueKind.Array;
                }

                if ((this.backing & Backing.Object) != 0)
                {
                    return JsonValueKind.Object;
                }

                return JsonValueKind.Undefined;
            }
        }

        /// <summary>
        /// Conversion from JsonAny.
        /// </summary>
        /// <param name="value">The value from which to convert.</param>
        public static implicit operator ObjPropListForGroup(JsonAny value)
        {
            return value.As<ObjPropListForGroup>();
        }

        /// <summary>
        /// Conversion to JsonAny.
        /// </summary>
        /// <param name="value">The value from which to convert.</param>
        public static implicit operator JsonAny(ObjPropListForGroup value)
        {
            return value.AsAny;
        }

        /// <summary>
        /// Conversion to <see cref="ACRealms.Roslyn.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropList"/>.
        /// </summary>
        /// <param name="value">The value from which to convert.</param>
        public static explicit operator ACRealms.Roslyn.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropList(ObjPropListForGroup value)
        {
            return value.As<ACRealms.Roslyn.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropList>();
        }

        /// <summary>
        /// Conversion from <see cref="ACRealms.Roslyn.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropList"/>.
        /// </summary>
        /// <param name="value">The value from which to convert.</param>
        public static implicit operator ObjPropListForGroup(ACRealms.Roslyn.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropList value)
        {
            return value.As<ObjPropListForGroup>();
        }

        /// <summary>
        /// Conversion to <see cref="ACRealms.Roslyn.RealmProps.IntermediateModels.RealmPropertySchema.ArrayShortPropListForGroup"/>.
        /// </summary>
        /// <param name="value">The value from which to convert.</param>
        public static explicit operator ACRealms.Roslyn.RealmProps.IntermediateModels.RealmPropertySchema.ArrayShortPropListForGroup(ObjPropListForGroup value)
        {
            return value.As<ACRealms.Roslyn.RealmProps.IntermediateModels.RealmPropertySchema.ArrayShortPropListForGroup>();
        }

        /// <summary>
        /// Conversion from <see cref="ACRealms.Roslyn.RealmProps.IntermediateModels.RealmPropertySchema.ArrayShortPropListForGroup"/>.
        /// </summary>
        /// <param name="value">The value from which to convert.</param>
        public static implicit operator ObjPropListForGroup(ACRealms.Roslyn.RealmProps.IntermediateModels.RealmPropertySchema.ArrayShortPropListForGroup value)
        {
            return value.As<ObjPropListForGroup>();
        }

        /// <summary>
        /// Operator ==.
        /// </summary>
        /// <param name="left">The lhs of the operator.</param>
        /// <param name="right">The rhs of the operator.</param>
        /// <returns>
        /// <c>True</c> if the values are equal.
        /// </returns>
        public static bool operator ==(in ObjPropListForGroup left, in ObjPropListForGroup right)
        {
            return left.Equals(right);
        }

        /// <summary>
        /// Operator !=.
        /// </summary>
        /// <param name="left">The lhs of the operator.</param>
        /// <param name="right">The rhs of the operator.</param>
        /// <returns>
        /// <c>True</c> if the values are not equal.
        /// </returns>
        public static bool operator !=(in ObjPropListForGroup left, in ObjPropListForGroup right)
        {
            return !left.Equals(right);
        }

        /// <summary>
        /// Gets an instance of the JSON value from a <see cref="JsonElement"/> value.
        /// </summary>
        /// <param name="value">The <see cref="JsonElement"/> value from which to instantiate the instance.</param>
        /// <returns>An instance of this type, initialized from the <see cref="JsonElement"/>.</returns>
        /// <remarks>The returned value will have a <see cref = "IJsonValue.ValueKind"/> of <see cref = "JsonValueKind.Undefined"/> if the
        /// value cannot be constructed from the given instance (e.g. because they have an incompatible .NET backing type).
        /// </remarks>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ObjPropListForGroup FromJson(in JsonElement value)
        {
            return new(value);
        }

        /// <summary>
        /// Gets an instance of the JSON value from a <see cref="JsonAny"/> value.
        /// </summary>
        /// <param name="value">The <see cref="JsonAny"/> value from which to instantiate the instance.</param>
        /// <returns>An instance of this type, initialized from the <see cref="JsonAny"/> value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ObjPropListForGroup FromAny(in JsonAny value)
        {
            if (value.HasJsonElementBacking)
            {
                return new(value.AsJsonElement);
            }

            return value.ValueKind switch
            {
                JsonValueKind.Array => new(value.AsArray.AsImmutableList()),
                JsonValueKind.Object => new(value.AsObject.AsPropertyBacking()),
                JsonValueKind.Null => Null,
                _ => Undefined,
            };
        }

#if NET8_0_OR_GREATER
        /// <summary>
        /// Gets an instance of the JSON value from the provided value.
        /// </summary>
        /// <typeparam name="TValue">The type of the value.</typeparam>
        /// <param name="value">The value from which to instantiate the instance.</param>
        /// <returns>An instance of this type, initialized from the provided value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        static ObjPropListForGroup IJsonValue<ObjPropListForGroup>.FromBoolean<TValue>(in TValue value)
        {
            if (value.HasJsonElementBacking)
            {
                return new(value.AsJsonElement);
            }

            return Undefined;
        }
#endif

#if NET8_0_OR_GREATER
        /// <summary>
        /// Gets an instance of the JSON value from the provided value.
        /// </summary>
        /// <typeparam name="TValue">The type of the value.</typeparam>
        /// <param name="value">The value from which to instantiate the instance.</param>
        /// <returns>An instance of this type, initialized from the provided value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        static ObjPropListForGroup IJsonValue<ObjPropListForGroup>.FromString<TValue>(in TValue value)
        {
            if (value.HasJsonElementBacking)
            {
                return new(value.AsJsonElement);
            }

            return Undefined;
        }
#endif

#if NET8_0_OR_GREATER
        /// <summary>
        /// Gets an instance of the JSON value from the provided value.
        /// </summary>
        /// <typeparam name="TValue">The type of the value.</typeparam>
        /// <param name="value">The value from which to instantiate the instance.</param>
        /// <returns>An instance of this type, initialized from the provided value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        static ObjPropListForGroup IJsonValue<ObjPropListForGroup>.FromNumber<TValue>(in TValue value)
        {
            if (value.HasJsonElementBacking)
            {
                return new(value.AsJsonElement);
            }

            return Undefined;
        }
#endif

        /// <summary>
        /// Gets an instance of the JSON value from the provided value.
        /// </summary>
        /// <typeparam name="TValue">The type of the value.</typeparam>
        /// <param name="value">The value from which to instantiate the instance.</param>
        /// <returns>An instance of this type, initialized from the provided value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ObjPropListForGroup FromObject<TValue>(in TValue value)
            where TValue : struct, IJsonObject<TValue>
        {
            if (value.HasJsonElementBacking)
            {
                return new(value.AsJsonElement);
            }

            return value.ValueKind switch
            {
                JsonValueKind.Object => new(value.AsPropertyBacking()),
                JsonValueKind.Null => Null,
                _ => Undefined,
            };
        }

        /// <summary>
        /// Gets an instance of the JSON value from the provided value.
        /// </summary>
        /// <typeparam name="TValue">The type of the value.</typeparam>
        /// <param name="value">The value from which to instantiate the instance.</param>
        /// <returns>An instance of this type, initialized from the provided value.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static ObjPropListForGroup FromArray<TValue>(in TValue value)
            where TValue : struct, IJsonArray<TValue>
        {
            if (value.HasJsonElementBacking)
            {
                return new(value.AsJsonElement);
            }

            return value.ValueKind switch
            {
                JsonValueKind.Array => new(value.AsImmutableList()),
                JsonValueKind.Null => Null,
                _ => Undefined,
            };
        }

        /// <summary>
        /// Parses the ObjPropListForGroup.
        /// </summary>
        /// <param name="source">The source of the JSON string to parse.</param>
        /// <param name="options">The (optional) JsonDocumentOptions.</param>
        public static ObjPropListForGroup Parse(string source, JsonDocumentOptions options = default)
        {
            using var jsonDocument = JsonDocument.Parse(source, options);
            return new(jsonDocument.RootElement.Clone());
        }

        /// <summary>
        /// Parses the ObjPropListForGroup.
        /// </summary>
        /// <param name="source">The source of the JSON string to parse.</param>
        /// <param name="options">The (optional) JsonDocumentOptions.</param>
        public static ObjPropListForGroup Parse(Stream source, JsonDocumentOptions options = default)
        {
            using var jsonDocument = JsonDocument.Parse(source, options);
            return new(jsonDocument.RootElement.Clone());
        }

        /// <summary>
        /// Parses the ObjPropListForGroup.
        /// </summary>
        /// <param name="source">The source of the JSON string to parse.</param>
        /// <param name="options">The (optional) JsonDocumentOptions.</param>
        public static ObjPropListForGroup Parse(ReadOnlyMemory<byte> source, JsonDocumentOptions options = default)
        {
            using var jsonDocument = JsonDocument.Parse(source, options);
            return new(jsonDocument.RootElement.Clone());
        }

        /// <summary>
        /// Parses the ObjPropListForGroup.
        /// </summary>
        /// <param name="source">The source of the JSON string to parse.</param>
        /// <param name="options">The (optional) JsonDocumentOptions.</param>
        public static ObjPropListForGroup Parse(ReadOnlyMemory<char> source, JsonDocumentOptions options = default)
        {
            using var jsonDocument = JsonDocument.Parse(source, options);
            return new(jsonDocument.RootElement.Clone());
        }

        /// <summary>
        /// Parses the ObjPropListForGroup.
        /// </summary>
        /// <param name="source">The source of the JSON string to parse.</param>
        /// <param name="options">The (optional) JsonDocumentOptions.</param>
        public static ObjPropListForGroup Parse(ReadOnlySequence<byte> source, JsonDocumentOptions options = default)
        {
            using var jsonDocument = JsonDocument.Parse(source, options);
            return new(jsonDocument.RootElement.Clone());
        }

        /// <summary>
        /// Parses the ObjPropListForGroup.
        /// </summary>
        /// <param name="source">The source of the JSON string to parse.</param>
        public static ObjPropListForGroup ParseValue(string source)
        {
#if NET8_0_OR_GREATER
            return IJsonValue<ObjPropListForGroup>.ParseValue(source);
#else
            return JsonValueHelpers.ParseValue<ObjPropListForGroup>(source.AsSpan());
#endif
        }

        /// <summary>
        /// Parses the ObjPropListForGroup.
        /// </summary>
        /// <param name="source">The source of the JSON string to parse.</param>
        public static ObjPropListForGroup ParseValue(ReadOnlySpan<char> source)
        {
#if NET8_0_OR_GREATER
            return IJsonValue<ObjPropListForGroup>.ParseValue(source);
#else
            return JsonValueHelpers.ParseValue<ObjPropListForGroup>(source);
#endif
        }

        /// <summary>
        /// Parses the ObjPropListForGroup.
        /// </summary>
        /// <param name="source">The source of the JSON string to parse.</param>
        public static ObjPropListForGroup ParseValue(ReadOnlySpan<byte> source)
        {
#if NET8_0_OR_GREATER
            return IJsonValue<ObjPropListForGroup>.ParseValue(source);
#else
            return JsonValueHelpers.ParseValue<ObjPropListForGroup>(source);
#endif
        }

        /// <summary>
        /// Parses the ObjPropListForGroup.
        /// </summary>
        /// <param name="source">The source of the JSON string to parse.</param>
        public static ObjPropListForGroup ParseValue(ref Utf8JsonReader source)
        {
#if NET8_0_OR_GREATER
            return IJsonValue<ObjPropListForGroup>.ParseValue(ref source);
#else
            return JsonValueHelpers.ParseValue<ObjPropListForGroup>(ref source);
#endif
        }

        /// <summary>
        /// Gets the value as an instance of the target value.
        /// </summary>
        /// <typeparam name="TTarget">The type of the target.</typeparam>
        /// <returns>An instance of the target type.</returns>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public TTarget As<TTarget>()
            where TTarget : struct, IJsonValue<TTarget>
        {
#if NET8_0_OR_GREATER
            if ((this.backing & Backing.JsonElement) != 0)
            {
                return TTarget.FromJson(this.jsonElementBacking);
            }

            if ((this.backing & Backing.Array) != 0)
            {
                return TTarget.FromArray(this.AsArray);
            }

            if ((this.backing & Backing.Object) != 0)
            {
                return TTarget.FromObject(this.AsObject);
            }

            if ((this.backing & Backing.Null) != 0)
            {
                return TTarget.Null;
            }

            return TTarget.Undefined;
#else
            return this.As<ObjPropListForGroup, TTarget>();
#endif
        }

        /// <inheritdoc/>
        public override bool Equals(object? obj)
        {
            return
                (obj is IJsonValue jv && this.Equals(jv.As<ObjPropListForGroup>())) ||
                (obj is null && this.IsNull());
        }

        /// <inheritdoc/>
        public bool Equals<T>(in T other)
            where T : struct, IJsonValue<T>
        {
            return this.Equals(other.As<ObjPropListForGroup>());
        }

        /// <summary>
        /// Equality comparison.
        /// </summary>
        /// <param name="other">The other item with which to compare.</param>
        /// <returns><see langword="true"/> if the values were equal.</returns>
        public bool Equals(in ObjPropListForGroup other)
        {
            JsonValueKind thisKind = this.ValueKind;
            JsonValueKind otherKind = other.ValueKind;
            if (thisKind != otherKind)
            {
                return false;
            }

            if (thisKind == JsonValueKind.Null || thisKind == JsonValueKind.Undefined)
            {
                return true;
            }

            if (thisKind == JsonValueKind.Array)
            {
                JsonArray thisArray = this.AsArray;
                JsonArray otherArray = other.AsArray;
                JsonArrayEnumerator lhs = thisArray.EnumerateArray();
                JsonArrayEnumerator rhs = otherArray.EnumerateArray();
                while (lhs.MoveNext())
                {
                    if (!rhs.MoveNext())
                    {
                        return false;
                    }

                    if (!lhs.Current.Equals(rhs.Current))
                    {
                        return false;
                    }
                }

                return !rhs.MoveNext();
            }

            if (thisKind == JsonValueKind.Object)
            {
                JsonObject thisObject = this.AsObject;
                JsonObject otherObject = other.AsObject;
                int count = 0;
                foreach (JsonObjectProperty property in thisObject.EnumerateObject())
                {
                    if (!otherObject.TryGetProperty(property.Name, out JsonAny value) || !property.Value.Equals(value))
                    {
                        return false;
                    }

                    count++;
                }

                int otherCount = 0;
                foreach (JsonObjectProperty otherProperty in otherObject.EnumerateObject())
                {
                    otherCount++;
                    if (otherCount > count)
                    {
                        return false;
                    }
                }

                return count == otherCount;
            }

            return false;
        }

        /// <inheritdoc/>
        public void WriteTo(Utf8JsonWriter writer)
        {
            if ((this.backing & Backing.JsonElement) != 0)
            {
                if (this.jsonElementBacking.ValueKind != JsonValueKind.Undefined)
                {
                    this.jsonElementBacking.WriteTo(writer);
                }

                return;
            }

            if ((this.backing & Backing.Array) != 0)
            {
                JsonValueHelpers.WriteItems(this.arrayBacking, writer);

                return;
            }

            if ((this.backing & Backing.Object) != 0)
            {
                JsonValueHelpers.WriteProperties(this.objectBacking, writer);

                return;
            }

            if ((this.backing & Backing.Null) != 0)
            {
                writer.WriteNullValue();

                return;
            }
        }

        /// <inheritdoc/>
        public override int GetHashCode()
        {
            return this.ValueKind switch
            {
                JsonValueKind.Array => JsonValueHelpers.GetArrayHashCode(this),
                JsonValueKind.Object => JsonValueHelpers.GetObjectHashCode(this),
                JsonValueKind.Number => JsonValueHelpers.GetHashCodeForNumber(((IJsonValue)this).AsNumber),
                JsonValueKind.String => JsonValueHelpers.GetHashCodeForString(((IJsonValue)this).AsString),
                JsonValueKind.True => true.GetHashCode(),
                JsonValueKind.False => false.GetHashCode(),
                JsonValueKind.Null => JsonValueHelpers.NullHashCode,
                _ => JsonValueHelpers.UndefinedHashCode,
            };
        }

        /// <inheritdoc/>
        public override string ToString()
        {
            return this.Serialize();
        }

        /// <summary>
        /// Matches the value against the composed values, and returns the result of calling the provided match function for the first match found.
        /// </summary>
        /// <typeparam name="TIn">The immutable context to pass in to the match function.</typeparam>
        /// <typeparam name="TOut">The result of calling the match function.</typeparam>
        /// <param name="context">The context to pass to the match function.</param>
        /// <param name="matchObjPropList">Match a <see cref="ACRealms.Roslyn.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropList"/>.</param>
        /// <param name="matchArrayShortPropListForGroup">Match a <see cref="ACRealms.Roslyn.RealmProps.IntermediateModels.RealmPropertySchema.ArrayShortPropListForGroup"/>.</param>
        /// <param name="defaultMatch">Match any other value.</param>
        /// <returns>An instance of the value returned by the match function.</returns>
        public TOut Match<TIn, TOut>(
            in TIn context,
            Matcher<ACRealms.Roslyn.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropList, TIn, TOut> matchObjPropList,
            Matcher<ACRealms.Roslyn.RealmProps.IntermediateModels.RealmPropertySchema.ArrayShortPropListForGroup, TIn, TOut> matchArrayShortPropListForGroup,
            Matcher<ACRealms.Roslyn.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropListForGroup, TIn, TOut> defaultMatch)
        {
            ACRealms.Roslyn.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropList matchObjPropListValue = this.As<ACRealms.Roslyn.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropList>();
            if (matchObjPropListValue.IsValid())
            {
                return matchObjPropList(matchObjPropListValue, context);
            }

            ACRealms.Roslyn.RealmProps.IntermediateModels.RealmPropertySchema.ArrayShortPropListForGroup matchArrayShortPropListForGroupValue = this.As<ACRealms.Roslyn.RealmProps.IntermediateModels.RealmPropertySchema.ArrayShortPropListForGroup>();
            if (matchArrayShortPropListForGroupValue.IsValid())
            {
                return matchArrayShortPropListForGroup(matchArrayShortPropListForGroupValue, context);
            }

            return defaultMatch(this, context);
        }

        /// <summary>
        /// Matches the value against the composed values, and returns the result of calling the provided match function for the first match found.
        /// </summary>
        /// <typeparam name="TOut">The result of calling the match function.</typeparam>
        /// <param name="matchObjPropList">Match a <see cref="ACRealms.Roslyn.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropList"/>.</param>
        /// <param name="matchArrayShortPropListForGroup">Match a <see cref="ACRealms.Roslyn.RealmProps.IntermediateModels.RealmPropertySchema.ArrayShortPropListForGroup"/>.</param>
        /// <param name="defaultMatch">Match any other value.</param>
        /// <returns>An instance of the value returned by the match function.</returns>
        public TOut Match<TOut>(
            Matcher<ACRealms.Roslyn.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropList, TOut> matchObjPropList,
            Matcher<ACRealms.Roslyn.RealmProps.IntermediateModels.RealmPropertySchema.ArrayShortPropListForGroup, TOut> matchArrayShortPropListForGroup,
            Matcher<ACRealms.Roslyn.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropListForGroup, TOut> defaultMatch)
        {
            ACRealms.Roslyn.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropList matchObjPropListValue = this.As<ACRealms.Roslyn.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropList>();
            if (matchObjPropListValue.IsValid())
            {
                return matchObjPropList(matchObjPropListValue);
            }

            ACRealms.Roslyn.RealmProps.IntermediateModels.RealmPropertySchema.ArrayShortPropListForGroup matchArrayShortPropListForGroupValue = this.As<ACRealms.Roslyn.RealmProps.IntermediateModels.RealmPropertySchema.ArrayShortPropListForGroup>();
            if (matchArrayShortPropListForGroupValue.IsValid())
            {
                return matchArrayShortPropListForGroup(matchArrayShortPropListForGroupValue);
            }

            return defaultMatch(this);
        }

        /// <summary>
        /// Gets the value as a <see cref="ACRealms.Roslyn.RealmProps.IntermediateModels.RealmPropertySchema.ArrayShortPropListForGroup" />.
        /// </summary>
        /// <param name="result">The result of the conversions.</param>
        /// <returns><see langword="true" /> if the conversion was valid.</returns>
        public bool TryGetAsArrayShortPropListForGroup(out ACRealms.Roslyn.RealmProps.IntermediateModels.RealmPropertySchema.ArrayShortPropListForGroup result)
        {
            result = this.As<ACRealms.Roslyn.RealmProps.IntermediateModels.RealmPropertySchema.ArrayShortPropListForGroup>();
            return result.IsValid();
        }

        /// <summary>
        /// Gets the value as a <see cref="ACRealms.Roslyn.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropList" />.
        /// </summary>
        /// <param name="result">The result of the conversions.</param>
        /// <returns><see langword="true" /> if the conversion was valid.</returns>
        public bool TryGetAsObjPropList(out ACRealms.Roslyn.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropList result)
        {
            result = this.As<ACRealms.Roslyn.RealmProps.IntermediateModels.RealmPropertySchema.ObjPropList>();
            return result.IsValid();
        }
    }
}
